// NOTE: this whole thing was autogenerated... wow!
#include <fstream>
#include <iostream>
#include <string>

class FileHandler {
public:
    static std::string readFile(const std::string& filename) {
        std::ifstream file(filename);
        if (!file.is_open()) {
            std::cerr << "Error opening file: " << filename << std::endl;
            return "";
        }
        std::string content((std::istreambuf_iterator<char>(file)), (std::istreambuf_iterator<char>()));
        file.close();
        return content;
    }

    static bool writeFile(const std::string& filename, const std::string& content) {
        std::ofstream file(filename);
        if (!file.is_open()) {
            std::cerr << "Error opening file: " << filename << std::endl;
            return false;
        }
        file << content;
        file.close();
        return true;
    }
};

int main(int argc, char** argv) {
    if (argc != 3) {
        std::cerr << "Usage: " << argv[0] << " <input_file> <output_file>" << std::endl;
        return 1;
    }
    std::string input_file(argv[1]);
    std::string output_file(argv[2]);
    std::string content = FileHandler::readFile(input_file);
    if (content.empty()) {
        return 1;
    }
    if (!FileHandler::writeFile(output_file, content)) {
        return 1;
    }
    return 0;
}
