#!/usr/bin/env python3
"""Pytest tests for the two functions in main.py.

TEST-SPACE PARTITIONS
====================
These are boundary and shape partitions, not an exhaustive Cartesian product.
Each named fixture has a reason, literal input, and handwritten expected output.
CASES.md shows them all with diagrams generated by visualize_cases.py; failure
messages include the same diagrams. Long axes explicitly say SKIPPED.
The diagrams contain fixture data only. Runtime printouts separately label YOUR
returned periods and EXPECTED fixture periods. For Part 2, the runner also calls
your Part 1 on a fresh copy of each camera's readings and prints its return value
or exception. These are separate diagnostic calls, not traced intermediates
inside Part 2, and their results add no assertions to the Part 2 test.
Pytest shows captured printouts on failure; use -s to see them on passing tests too.

Part 1 (40 cases)
----------------
* Cardinality/activity: no readings; one reading below/equal/above; multiple
  readings never active, always strictly above, always equal, or mixed equal/above.
* Location/length of runs: singletons and longer runs at the start, in the
  middle, or at the end. Equality is tested at all singleton positions and in
  longer runs, at both endpoints, and between strictly active readings.
* Transitions: one inactive reading splits two runs; multiple inactive readings;
  alternating activity starting on either side; several runs of mixed lengths.
* Time boundaries/sampling: start/end use the first/last qualifying reading,
  not the neighboring inactive reading; wide sampling gaps alone do not split
  a run; a real inactive reading does; timestamp zero and large timestamp values.
* Thresholds: 0, 1, a nondefault 0.5, equality, and values just above/below 0.8.
  No epsilon or rounding is part of the comparison contract.
* Discrete-contract boundary: fractional inactive samples split raw runs even
  when their active integer endpoints are adjacent. Part 1 preserves those runs.
* The supplied interview example, whose expected output is copied verbatim.

Part 2 (63 cases)
----------------
* Camera cardinality: zero, one, two, three, four, five; an empty camera, all
  cameras empty, a camera with only inactive readings, all cameras inactive,
  and a duplicate stream. Zero cameras is explicitly defined to return [].
* One-period geometry: disjoint in either ordering; adjacent but NOT overlapping;
  identical; nested in either ordering; partial overlap in either ordering;
  equal starts or ends; a shared endpoint; singleton inside/at start/at end;
  singleton versus singleton at equal or different timestamps.
* Multiplicity: one, two, or three intersections on one segment. Two endpoint
  overlaps [2,2] and [4,4] stay separate because tick 3 is missing. Two adjacent
  pieces [2,3] and [4,4] become [2,4]. Adjacent singletons also merge. Even one
  missing integer prevents merging. Adjacency never substitutes for overlap
  between different cameras.
* Chains: three pieces forming one period; merge/gap/merge; another chain later;
  fragmentation in both cameras; changing which camera ends first; tied ends
  followed by later activity; repeated endpoint-only overlaps; unmatched heads
  and tails; interleaved runs with no intersection at all.
* All-camera requirement: the first two intersect but a third does not; every
  PAIR intersects but the three-way result is empty; a later camera deletes,
  trims, or splits previous common activity; all cameras meet at just one tick;
  staggered fragments in three streams; a fifth camera blocks everything.
* Sampling/values: no shared reading timestamps despite overlapping periods;
  sparse sampling; zero/large timestamps; equality at intersection boundaries;
  equal singletons; just-below values; thresholds 0, 1, and nondefault 0.5.
* Camera order: each multi-camera fixture also runs reversed and rotated, with
  identical permutations deduplicated. These reuse its diagram and expected
  answer and make no assumption about the first camera's size or start time.

CONTRACT AND LIMITS
==================
Follow README.md: timestamps are strictly increasing per stream. Qualifying
sample timestamps are integer ticks, inactive samples may include half ticks,
and intensity/threshold lie in [0,1]. Part 1 reports raw consecutive active runs;
Part 2 reports maximal inclusive INTEGER coverage. Thus fractional inactivity
can separate Part 1 runs without creating a missing integer in Part 2.
There is no input validation, duplicate-timestamp, continuous-time, tolerance,
or maximum-size/performance requirement. Those were not specified. Empty input
behavior and integer normalization are explicit local practice conventions.
Apart from the supplied example, expectations are authored fixtures, not claimed
official interview tests. There is no reference solver or expected-output
calculation in this runner. The two NotImplementedError stubs initially fail
every case. Each call receives a fresh copy of its input, so changes made by an
implementation cannot corrupt later fixtures or the camera-order checks.

RUN (from this folder)
=====================
python3 -m pytest -q                        # both parts
python3 -m pytest -q -k part1                # Part 1 only
python3 -m pytest -q -k part2                # Part 2 only
python3 -m pytest -v -k adjacent             # matching case names
python3 -m pytest -x                        # stop at first failure
python3 -m pytest -s -v -k threshold_one_split_overlap  # show runtime printouts

Only main.py contains the two functions to implement. There is no compilation
step, subprocess, temporary build directory, or reference implementation.
Requires Python 3.8+ and pytest (see requirements-dev.txt).
"""

from copy import deepcopy

import pytest

from cases import PART1_CASES, PART2_CASES
from main import find_active_periods, find_common_active_periods
from visualize_cases import describe_case


def check_result(function, argument, case, order="original camera order"):
    part = "Part 1" if case.camera_periods is None else "Part 2"
    print("\n[{}] {} | {}".format(case.name, part, order))
    print("EXPECTED {} periods (fixture): {!r}".format(part, case.expected))
    detail = "\n{} ({})\nFIXTURE DATA AND EXPECTED DIAGRAM (not your output):\n{}".format(
        case.name, order, describe_case(case)
    )
    try:
        actual = function(deepcopy(argument), case.threshold)
    except NotImplementedError as error:
        print("YOUR {} raised {}: {}".format(part, type(error).__name__, error))
        pytest.fail(str(error) + detail, pytrace=False)
    except Exception as error:
        # Pytest displays captured stdout on failure, alongside the traceback.
        print("YOUR {} raised {}: {}".format(part, type(error).__name__, error))
        print(detail)
        raise
    print("YOUR {} returned periods: {!r}".format(part, actual))
    assert actual == case.expected, detail


def print_part1_diagnostics(case):
    print("\n[{}] YOUR PART 1: separate diagnostic calls per camera".format(case.name))
    print("Camera numbers below match the original fixture/diagram order.")
    print("threshold = {!r}".format(case.threshold))
    if not case.streams:
        print("No cameras; no Part 1 calls.")
    for number, (stream, expected) in enumerate(
        zip(case.streams, case.camera_periods), start=1
    ):
        print("\ncamera{} readings: {!r}".format(number, stream))
        print("  EXPECTED Part 1 periods (fixture): {!r}".format(expected))
        try:
            actual = find_active_periods(deepcopy(stream), case.threshold)
        except Exception as error:
            # Diagnostics must not prevent testing an independent Part 2.
            print("  YOUR Part 1 raised {}: {}".format(type(error).__name__, error))
        else:
            print("  YOUR Part 1 returned periods: {!r}".format(actual))


@pytest.mark.parametrize("case", PART1_CASES, ids=lambda case: case.name)
def test_part1(case):
    check_result(find_active_periods, case.streams[0], case)


@pytest.mark.parametrize("case", PART2_CASES, ids=lambda case: case.name)
def test_part2(case):
    print_part1_diagnostics(case)
    check_result(find_common_active_periods, case.streams, case)
    if len(case.streams) > 1:
        seen = [case.streams]
        variants = [
            ("reversed cameras", list(reversed(case.streams))),
            ("rotated cameras", case.streams[1:] + case.streams[:1]),
        ]
        for label, streams in variants:
            if streams not in seen:
                seen.append(streams)
                check_result(find_common_active_periods, streams, case, label)
