#!/usr/bin/env python3
"""Draw small, inclusive integer timelines from the declared test fixtures.

This only displays supplied readings and interval literals. It neither discovers
active runs nor calculates intersections or expected answers. x means active,
a dash is absent; a dot is an explicitly inactive sample. Raw sample rows distinguish
missing observations from inactivity. Fractional inactive samples are listed
separately, since the coverage rows describe integer ticks.

Long axes print SKIPPED: default limits are 40 ticks and 120 output columns.
Use --write to regenerate CASES.md, or filter with --part and --match.
"""

import argparse
from pathlib import Path

from cases import PART1_CASES, PART2_CASES


def draw_case(case, max_ticks=40, max_width=120):
    streams = case.streams
    timestamps = [time for stream in streams for time, _ in stream]
    if not timestamps:
        return "(empty timeline: no readings; expected [])"

    first = int(min(timestamps))
    last = int(max(timestamps))
    if max(timestamps) != last:
        last += 1
    tick_count = last - first + 1
    cell_width = max(len(str(first)), len(str(last))) + 1
    label_width = 12
    total_width = label_width + tick_count * cell_width
    if tick_count > max_ticks or total_width > max_width:
        return "SKIPPED: {} integer ticks / {} columns; limits {} ticks / {} columns.".format(
            tick_count, total_width, max_ticks, max_width
        )

    ticks = range(first, last + 1)

    def row(label, symbols):
        return label.ljust(label_width) + "".join(
            str(symbol).rjust(cell_width) for symbol in symbols
        )

    def interval_row(label, periods):
        # Rendering supplied interval literals, not finding or intersecting runs.
        return row(
            label,
            [
                "x" if any(start <= tick <= end for start, end in periods) else "-"
                for tick in ticks
            ],
        )

    lines = [row("tick", ticks)]
    fractional = []
    for number, stream in enumerate(streams, start=1):
        samples = dict(stream)
        lines.append(
            row(
                "c{} samples".format(number),
                [
                    (
                        "-"
                        if tick not in samples
                        else "x" if samples[tick] >= case.threshold else "."
                    )
                    for tick in ticks
                ],
            )
        )
        if case.camera_periods is not None:
            lines.append(
                interval_row(
                    "c{} periods".format(number), case.camera_periods[number - 1]
                )
            )
        for timestamp, intensity in stream:
            if timestamp != int(timestamp):
                fractional.append("c{}: ({}, {})".format(number, timestamp, intensity))
    lines.append(interval_row("expected", case.expected))
    if fractional:
        lines.append("Off-grid inactive samples: " + "; ".join(fractional))
    return "\n".join(lines)


def describe_case(case, max_ticks=40, max_width=120):
    lines = [case.reason, "threshold = {}".format(case.threshold)]
    for number, stream in enumerate(case.streams, start=1):
        lines.append("camera{} readings = {}".format(number, stream))
        if case.camera_periods is not None:
            lines.append(
                "camera{} declared periods = {}".format(
                    number, case.camera_periods[number - 1]
                )
            )
    if not case.streams:
        lines.append("camera_streams = []")
    lines.append("expected = {}".format(case.expected))
    lines.extend(["", draw_case(case, max_ticks, max_width)])
    return "\n".join(lines)


def render_catalog(selected, max_ticks=40, max_width=120):
    lines = [
        "# Motion test cases",
        "",
        "Generated by `visualize_cases.py` from the handwritten fixtures in `cases.py`.",
        "Expected answers are literal fixtures, never computed by the visualizer.",
        "",
        "On the integer grid, `x` means active coverage and `-` means absent coverage.",
        "In sample rows, `x` means at or above threshold, `.` means below threshold,",
        "and `-` means no reading.",
        "Period rows include unsampled integer ticks within the declared interval bounds.",
        "Fractional inactive readings are listed separately. Part 1 preserves distinct raw runs;",
        "Part 2 merges adjacent integer output periods. Consult README.md for this chosen contract.",
        "Long diagrams say `SKIPPED`; their inputs and expected outputs remain listed.",
        "",
    ]
    for part, case in selected:
        lines.extend(
            [
                "## Part {}: {}".format(part, case.name),
                "",
                "```text",
                describe_case(case, max_ticks, max_width),
                "```",
                "",
            ]
        )
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--part", type=int, choices=(1, 2))
    parser.add_argument("--match", default="", help="substring of case name")
    parser.add_argument("--max-ticks", type=int, default=40)
    parser.add_argument("--max-width", type=int, default=120)
    parser.add_argument("--write", type=Path, help="write the catalog to this path")
    args = parser.parse_args()
    if args.max_ticks < 1 or args.max_width < 1:
        parser.error("diagram limits must be positive")
    selected = [
        (part, case)
        for part, cases in ((1, PART1_CASES), (2, PART2_CASES))
        for case in cases
        if (args.part is None or args.part == part) and args.match in case.name
    ]
    if not selected:
        parser.error("no matching cases")
    output = render_catalog(selected, args.max_ticks, args.max_width)
    if args.write:
        args.write.write_text(output, encoding="utf-8")
        print("Wrote {} cases to {}".format(len(selected), args.write))
    else:
        print(output)


if __name__ == "__main__":
    main()
